In [16]:
import os
import numpy as np
import pandas as pd
import openpyxl

## Conjunto de Dados - CORONAVÍRUS BRASIL
https://covid.saude.gov.br/

In [17]:
diretorio  = 'Dataset/hist'

In [18]:
df_dados          = pd.DataFrame()    
df_df = pd.DataFrame()
lista_arquivos    = []

# Lista os arquivos do diretório
for arquivo in os.listdir(diretorio):
    if arquivo.endswith('.csv'):
       lista_arquivos.append(arquivo) 
       
# Carrega o DataFrame 
for dataset in lista_arquivos:
    caminho_arquivo   = os.path.join(diretorio, dataset)
    df_dados          = pd.read_csv(caminho_arquivo, sep=';', low_memory=False)
    df_df = pd.concat([df_df, df_dados], ignore_index=True)

In [19]:
df_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7204426 entries, 0 to 7204425
Data columns (total 17 columns):
 #   Column                  Dtype
---  ------                  -----
 0   regiao                  object
 1   estado                  object
 2   municipio               object
 3   coduf                   int64
 4   codmun                  float64
 5   codRegiaoSaude          float64
 6   nomeRegiaoSaude         object
 7   data                    object
 8   semanaEpi               int64
 9   populacaoTCU2019        float64
 10  casosAcumulado          float64
 11  casosNovos              int64
 12  obitosAcumulado         int64
 13  obitosNovos             int64
 14  Recuperadosnovos        float64
 15  emAcompanhamentoNovos   float64
 16  interior/metropolitana  float64
dtypes: float64(7), int64(5), object(5)
memory usage: 934.4+ MB

In [20]:
df_fora_do_DF = df_df[df_df['estado'] != 'DF'].index
df_df       = df_df.drop(df_fora_do_DF)

In [21]:
df_df.isnull().sum()

regiao                       0
estado                       0
municipio                 1313
coduf                        0
codmun                    1313
codRegiaoSaude            1313
nomeRegiaoSaude           1313
data                         0
semanaEpi                    0
populacaoTCU2019             0
casosAcumulado               0
casosNovos                   0
obitosAcumulado              0
obitosNovos                  0
Recuperadosnovos          2595
emAcompanhamentoNovos     2595
interior/metropolitana    1313
dtype: int64

In [22]:
df_df.dropna(subset=['nomeRegiaoSaude'], inplace = True)

In [23]:
df_df

,regiao,estado,municipio,coduf,codmun,codRegiaoSaude,nomeRegiaoSaude,data,semanaEpi,populacaoTCU2019,casosAcumulado,casosNovos,obitosAcumulado,obitosNovos,Recuperadosnovos,emAcompanhamentoNovos,interior/metropolitana
714354,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2020-03-27,13,3015268.0,0.0,0,0,0,NaN,NaN,1.0
714355,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2020-03-28,13,3015268.0,260.0,260,0,0,NaN,NaN,1.0
714356,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2020-03-29,14,3015268.0,289.0,29,1,1,NaN,NaN,1.0
714357,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2020-03-30,14,3015268.0,312.0,23,1,0,NaN,NaN,1.0
714358,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2020-03-31,14,3015268.0,332.0,20,3,2,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7204421,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2023-09-25,39,3015268.0,916276.0,0,11896,0,NaN,NaN,1.0
7204422,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2023-09-26,39,3015268.0,916276.0,0,11896,0,NaN,NaN,1.0
7204423,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2023-09-27,39,3015268.0,916276.0,0,11896,0,NaN,NaN,1.0
7204424,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2023-09-28,39,3015268.0,916276.0,0,11896,0,NaN,NaN,1.0
7204425,Centro-Oeste,DF,Brasília,53,530010.0,53001.0,DISTRITO FEDERAL,2023-09-29,39,3015268.0,916276.0,0,11896,0,NaN,NaN,1.0

In [24]:
df_int = df_df[['data','casosAcumulado','obitosAcumulado']]

In [25]:
df_int.loc[:, 'data'] = pd.to_datetime(df_int['data'])

In [26]:
df_int.loc[:,'casosAcumulado'] = df_int['casosAcumulado'].astype(int)

In [27]:
df_int.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1282 entries, 714354 to 7204425
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data             1282 non-null   object
 1   casosAcumulado   1282 non-null   float64
 2   obitosAcumulado  1282 non-null   int64
dtypes: float64(1), int64(1), object(1)
memory usage: 40.1+ KB

In [28]:
df_int

                        data  casosAcumulado  obitosAcumulado
714354   2020-03-27 00:00:00             0.0                0
714355   2020-03-28 00:00:00           260.0                0
714356   2020-03-29 00:00:00           289.0                1
714357   2020-03-30 00:00:00           312.0                1
714358   2020-03-31 00:00:00           332.0                3
...                      ...             ...              ...
7204421  2023-09-25 00:00:00        916276.0            11896
7204422  2023-09-26 00:00:00        916276.0            11896
7204423  2023-09-27 00:00:00        916276.0            11896
7204424  2023-09-28 00:00:00        916276.0            11896
7204425  2023-09-29 00:00:00        916276.0            11896

[1282 rows x 3 columns]

In [14]:
df_int.to_csv('Dados_covid_DF', index=False)